{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4e5caf3f-7e69-44ea-9a7b-9f2d237af1d2",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import random\n",
    "\n",
    "# ==========================================\n",
    "# 0. 페이지 설정\n",
    "# ==========================================\n",
    "st.set_page_config(page_title=\"마피아 게임 도우미\", page_icon=\"🕵️\", layout=\"centered\")\n",
    "\n",
    "# ==========================================\n",
    "# 1. 세션 상태 초기화\n",
    "# ==========================================\n",
    "special_roles_pool = [\"🪖 군인\", \"🏛️ 정치인\", \"📰 기자\", \"🔍 탐정\"]\n",
    "night_order = [\"스파이\", \"마피아\", \"의사\", \"경찰\", \"기자\", \"탐정\"]\n",
    "\n",
    "def init_session_state():\n",
    "    defaults = {\n",
    "        'phase': 'setup',\n",
    "        'roles': [],\n",
    "        'draw_log': [],\n",
    "        'player_number': 1,\n",
    "        'players_info': {},\n",
    "        'day': 1,\n",
    "        'is_night': True,\n",
    "        'spy_connected': False,\n",
    "        'night_queue': [],\n",
    "        'current_night_role': None,\n",
    "        'night_targets': {},\n",
    "        'reporter_used': False,\n",
    "        'reporter_target_day': None,\n",
    "        'sys_msgs': []\n",
    "    }\n",
    "    for key, val in defaults.items():\n",
    "        if key not in st.session_state:\n",
    "            st.session_state[key] = val\n",
    "\n",
    "init_session_state()\n",
    "\n",
    "# ==========================================\n",
    "# 2. 게임 로직\n",
    "# ==========================================\n",
    "def setup_roles(count):\n",
    "    base = [\"🕵️ 마피아\", \"👮 경찰\", \"💉 의사\", \"🙂 시민\"]\n",
    "    if count == 5: base.append(\"🙂 시민\")\n",
    "    elif count == 6: base += [\"🙂 시민\", \"🕶️ 스파이\"]\n",
    "    elif count == 7:\n",
    "        base.append(\"🕵️ 마피아\")\n",
    "        base += random.sample(special_roles_pool, 2)\n",
    "    elif count == 8:\n",
    "        base.append(\"🕵️ 마피아\")\n",
    "        base += random.sample(special_roles_pool, 2)\n",
    "        base.append(\"🕶️ 스파이\")\n",
    "    return base\n",
    "\n",
    "def log_msg(msg):\n",
    "    st.session_state.sys_msgs.insert(0, msg)\n",
    "\n",
    "def get_alive_roles():\n",
    "    alive = []\n",
    "    for pid, pinfo in st.session_state.players_info.items():\n",
    "        if pinfo['alive']:\n",
    "            for role_name in night_order:\n",
    "                if role_name in pinfo['role']:\n",
    "                    alive.append(role_name)\n",
    "    return list(set(alive))\n",
    "\n",
    "def check_win():\n",
    "    mafia_count = 0\n",
    "    citizen_count = 0\n",
    "    for pid, pinfo in st.session_state.players_info.items():\n",
    "        if not pinfo['alive']: continue\n",
    "        role = pinfo['role']\n",
    "        if \"마피아\" in role:\n",
    "            mafia_count += 1\n",
    "        elif \"스파이\" in role:\n",
    "            if st.session_state.spy_connected: mafia_count += 1\n",
    "        else:\n",
    "            if \"정치인\" in role: citizen_count += 2\n",
    "            else: citizen_count += 1\n",
    "\n",
    "    if mafia_count == 0: return \"🎉 시민 승리!\"\n",
    "    elif mafia_count >= citizen_count: return \"💀 마피아 승리!\"\n",
    "    return None\n",
    "\n",
    "def kill_player(pid):\n",
    "    st.session_state.players_info[pid]['alive'] = False\n",
    "    if \"스파이\" in st.session_state.players_info[pid]['role'] and not st.session_state.spy_connected:\n",
    "        return \"스파이_사망\"\n",
    "    return \"사망\"\n",
    "\n",
    "# --- 버튼 콜백 ---\n",
    "def cb_set_roles(count):\n",
    "    st.session_state.roles = setup_roles(count)\n",
    "    st.session_state.draw_log = []\n",
    "    st.session_state.player_number = 1\n",
    "    st.session_state.sys_msgs = [f\"👥 {count}인 역할이 설정되었습니다. 역할을 뽑아주세요.\"]\n",
    "\n",
    "def cb_draw_role():\n",
    "    if st.session_state.roles:\n",
    "        picked = random.choice(st.session_state.roles)\n",
    "        st.session_state.roles.remove(picked)\n",
    "        pnum = st.session_state.player_number\n",
    "        log_entry = f\"플레이어 {pnum} → {picked}\"\n",
    "        st.session_state.draw_log.append(log_entry)\n",
    "        \n",
    "        st.session_state.players_info[pnum] = {\n",
    "            \"role\": picked,\n",
    "            \"alive\": True,\n",
    "            \"shield\": \"군인\" in picked\n",
    "        }\n",
    "        \n",
    "        st.session_state.sys_msgs = [f\"🎉 {log_entry} (남은 직업: {len(st.session_state.roles)}개)\"]\n",
    "        st.session_state.player_number += 1\n",
    "\n",
    "def cb_start_game():\n",
    "    st.session_state.phase = 'game'\n",
    "    st.session_state.day = 1\n",
    "    st.session_state.is_night = True\n",
    "    cb_start_night_phase()\n",
    "\n",
    "def cb_reset():\n",
    "    for key in st.session_state.keys():\n",
    "        del st.session_state[key]\n",
    "    init_session_state()\n",
    "\n",
    "def cb_start_night_phase():\n",
    "    st.session_state.night_targets = {}\n",
    "    st.session_state.current_night_role = None\n",
    "    alive_roles = get_alive_roles()\n",
    "    st.session_state.night_queue = [role for role in night_order if role in alive_roles]\n",
    "    st.session_state.sys_msgs = [f\"🌙 {st.session_state.day}일차 밤이 되었습니다. [다음 직업]을 눌러주세요.\"]\n",
    "\n",
    "def cb_next_night_action():\n",
    "    if not st.session_state.night_queue:\n",
    "        st.session_state.current_night_role = None\n",
    "        st.session_state.sys_msgs = [\"🌙 모든 밤 행동이 끝났습니다. [낮/밤 전환] 버튼을 누르세요.\"]\n",
    "        return\n",
    "\n",
    "    role = st.session_state.night_queue.pop(0)\n",
    "    st.session_state.current_night_role = role\n",
    "    msg = f\"🌙 [{role}]은(는) 밤 행동을 취하십시오.\\n\"\n",
    "    st.session_state.sys_msgs = [msg]\n",
    "\n",
    "def cb_process_night_results():\n",
    "    log_msg(f\"☀️ {st.session_state.day}일차 아침이 밝았습니다.\")\n",
    "    targets = st.session_state.night_targets\n",
    "    pinfo = st.session_state.players_info\n",
    "    \n",
    "    if \"마피아\" in targets:\n",
    "        target_pid = targets[\"마피아\"]\n",
    "        target_role = pinfo[target_pid]['role']\n",
    "        \n",
    "        if \"의사\" in targets and targets[\"의사\"] == target_pid:\n",
    "            log_msg(\"💉 의사의 활약으로 간밤에 아무도 죽지 않았습니다!\")\n",
    "        elif \"군인\" in target_role and pinfo[target_pid].get('shield', False):\n",
    "            pinfo[target_pid]['shield'] = False\n",
    "            log_msg(f\"🪖 군인(플레이어 {target_pid})님이 마피아의 공격을 버텼습니다!\")\n",
    "        else:\n",
    "            log_msg(f\"💀 밤 사이 플레이어 {target_pid}님이 사망했습니다.\")\n",
    "            kill_player(target_pid)\n",
    "    else:\n",
    "        log_msg(\"🕊️ 간밤에 아무도 죽지 않았습니다.\")\n",
    "\n",
    "    win = check_win()\n",
    "    if win: log_msg(f\"🏆 {win}\")\n",
    "\n",
    "def cb_toggle_day_night():\n",
    "    if st.session_state.is_night:\n",
    "        st.session_state.is_night = False\n",
    "        cb_process_night_results()\n",
    "    else:\n",
    "        st.session_state.day += 1\n",
    "        st.session_state.is_night = True\n",
    "        cb_start_night_phase()\n",
    "\n",
    "def cb_player_click(pid):\n",
    "    pinfo = st.session_state.players_info[pid]\n",
    "    kill_player(pid)\n",
    "    log_msg(f\"⚖️ 투표 결과: 플레이어 {pid}님이 처형되었습니다.\")\n",
    "    win = check_win()\n",
    "    if win: log_msg(f\"🏆 {win}\")\n",
    "\n",
    "# ==========================================\n",
    "# 3. UI 렌더링\n",
    "# ==========================================\n",
    "st.title(\"🕵️ 마피아 게임 도우미\")\n",
    "\n",
    "if st.session_state.phase == 'setup':\n",
    "    col1, col2 = st.columns([1, 1])\n",
    "    with col1:\n",
    "        p_count = st.selectbox(\"인원수 설정\", [4, 5, 6, 7, 8], index=0)\n",
    "    with col2:\n",
    "        st.button(\"👥 설정 적용\", on_click=cb_set_roles, args=(p_count,), use_container_width=True)\n",
    "\n",
    "    st.button(\"🎭 역할 뽑기\", on_click=cb_draw_role, disabled=len(st.session_state.roles)==0)\n",
    "\n",
    "    if st.session_state.sys_msgs:\n",
    "        st.info(st.session_state.sys_msgs[0])\n",
    "\n",
    "    if len(st.session_state.draw_log) == p_count and len(st.session_state.roles) == 0:\n",
    "        st.success(\"🎊 모든 역할이 배정되었습니다!\")\n",
    "        st.button(\"▶️ 게임 시작\", on_click=cb_start_game)\n",
    "\n",
    "elif st.session_state.phase == 'game':\n",
    "    st.button(\"🔄 리셋\", on_click=cb_reset)\n",
    "    st.button(\"⏭ 낮/밤 전환\", on_click=cb_toggle_day_night)\n",
    "\n",
    "    st.write(\"### 플레이어 목록\")\n",
    "    for pid, pinfo in st.session_state.players_info.items():\n",
    "        btn_label = f\"P{pid} ({pinfo['role']})\"\n",
    "        if not pinfo['alive']: btn_label += \" 💀\"\n",
    "        st.button(btn_label, key=f\"pbtn_{pid}\", on_click=cb_player_click, args=(pid,))"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
