{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4e5caf3f-7e69-44ea-9a7b-9f2d237af1d2",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import random\n",
    "\n",
    "# ==========================================\n",
    "# 0. 페이지 설정 (스마트폰 화면에 맞게)\n",
    "# ==========================================\n",
    "st.set_page_config(page_title=\"마피아 게임 도우미\", page_icon=\"🕵️\", layout=\"centered\")\n",
    "\n",
    "# ==========================================\n",
    "# 1. 고정 데이터 및 세션 상태 초기화\n",
    "# ==========================================\n",
    "special_roles_pool = [\"🪖 군인\", \"🏛️ 정치인\", \"📰 기자\", \"🔍 탐정\"]\n",
    "night_order = [\"스파이\", \"마피아\", \"의사\", \"경찰\", \"기자\", \"탐정\"]\n",
    "\n",
    "def init_session_state():\n",
    "    defaults = {\n",
    "        'phase': 'setup', # 'setup' or 'game'\n",
    "        'roles': [],\n",
    "        'draw_log': [],\n",
    "        'player_number': 1,\n",
    "        'players_info': {},\n",
    "        'day': 1,\n",
    "        'is_night': True,\n",
    "        'spy_connected': False,\n",
    "        'night_queue': [],\n",
    "        'current_night_role': None,\n",
    "        'night_targets': {},\n",
    "        'reporter_used': False,\n",
    "        'reporter_target_day': None,\n",
    "        'sys_msgs': [] # 시스템 메시지 로그\n",
    "    }\n",
    "    for key, val in defaults.items():\n",
    "        if key not in st.session_state:\n",
    "            st.session_state[key] = val\n",
    "\n",
    "init_session_state()\n",
    "\n",
    "# ==========================================\n",
    "# 2. 게임 로직 (콜백 함수 및 유틸)\n",
    "# ==========================================\n",
    "def setup_roles(count):\n",
    "    base = [\"🕵️ 마피아\", \"👮 경찰\", \"💉 의사\", \"🙂 시민\"]\n",
    "    if count == 5: base.append(\"🙂 시민\")\n",
    "    elif count == 6: base += [\"🙂 시민\", \"🕶️ 스파이\"]\n",
    "    elif count == 7:\n",
    "        base.append(\"🕵️ 마피아\")\n",
    "        base += random.sample(special_roles_pool, 2)\n",
    "    elif count == 8:\n",
    "        base.append(\"🕵️ 마피아\")\n",
    "        base += random.sample(special_roles_pool, 2)\n",
    "        base.append(\"🕶️ 스파이\")\n",
    "    return base\n",
    "\n",
    "def log_msg(msg):\n",
    "    st.session_state.sys_msgs.insert(0, msg)\n",
    "\n",
    "def get_alive_roles():\n",
    "    alive = []\n",
    "    for pid, pinfo in st.session_state.players_info.items():\n",
    "        if pinfo['alive']:\n",
    "            for role_name in night_order:\n",
    "                if role_name in pinfo['role']:\n",
    "                    alive.append(role_name)\n",
    "    return list(set(alive))\n",
    "\n",
    "def check_win():\n",
    "    mafia_count = 0\n",
    "    citizen_count = 0\n",
    "    for pid, pinfo in st.session_state.players_info.items():\n",
    "        if not pinfo['alive']: continue\n",
    "        role = pinfo['role']\n",
    "        if \"마피아\" in role:\n",
    "            mafia_count += 1\n",
    "        elif \"스파이\" in role:\n",
    "            if st.session_state.spy_connected: mafia_count += 1\n",
    "        else:\n",
    "            if \"정치인\" in role: citizen_count += 2\n",
    "            else: citizen_count += 1\n",
    "\n",
    "    if mafia_count == 0: return \"🎉 시민 승리!\"\n",
    "    elif mafia_count >= citizen_count: return \"💀 마피아 승리!\"\n",
    "    return None\n",
    "\n",
    "def kill_player(pid):\n",
    "    st.session_state.players_info[pid]['alive'] = False\n",
    "    if \"스파이\" in st.session_state.players_info[pid]['role'] and not st.session_state.spy_connected:\n",
    "        return \"스파이_사망\"\n",
    "    return \"사망\"\n",
    "\n",
    "# --- 버튼 콜백 함수들 ---\n",
    "def cb_set_roles(count):\n",
    "    st.session_state.roles = setup_roles(count)\n",
    "    st.session_state.draw_log = []\n",
    "    st.session_state.player_number = 1\n",
    "    st.session_state.sys_msgs = [f\"👥 {count}인 역할이 설정되었습니다. 역할을 뽑아주세요.\"]\n",
    "\n",
    "def cb_draw_role():\n",
    "    if st.session_state.roles:\n",
    "        picked = random.choice(st.session_state.roles)\n",
    "        st.session_state.roles.remove(picked)\n",
    "        pnum = st.session_state.player_number\n",
    "        log_entry = f\"플레이어 {pnum} → {picked}\"\n",
    "        st.session_state.draw_log.append(log_entry)\n",
    "        \n",
    "        # 플레이어 데이터 사전 세팅\n",
    "        st.session_state.players_info[pnum] = {\n",
    "            \"role\": picked,\n",
    "            \"alive\": True,\n",
    "            \"shield\": \"군인\" in picked\n",
    "        }\n",
    "        \n",
    "        st.session_state.sys_msgs = [f\"🎉 {log_entry} (남은 직업: {len(st.session_state.roles)}개)\"]\n",
    "        st.session_state.player_number += 1\n",
    "\n",
    "def cb_start_game():\n",
    "    st.session_state.phase = 'game'\n",
    "    st.session_state.day = 1\n",
    "    st.session_state.is_night = True\n",
    "    cb_start_night_phase()\n",
    "\n",
    "def cb_reset():\n",
    "    for key in st.session_state.keys():\n",
    "        del st.session_state[key]\n",
    "    init_session_state()\n",
    "\n",
    "def cb_start_night_phase():\n",
    "    st.session_state.night_targets = {}\n",
    "    st.session_state.current_night_role = None\n",
    "    alive_roles = get_alive_roles()\n",
    "    st.session_state.night_queue = [role for role in night_order if role in alive_roles]\n",
    "    st.session_state.sys_msgs = [f\"🌙 {st.session_state.day}일차 밤이 되었습니다. [다음 직업]을 눌러주세요.\"]\n",
    "\n",
    "def cb_next_night_action():\n",
    "    if not st.session_state.night_queue:\n",
    "        st.session_state.current_night_role = None\n",
    "        st.session_state.sys_msgs = [\"🌙 모든 밤 행동이 끝났습니다. [낮/밤 전환] 버튼을 누르세요.\"]\n",
    "        return\n",
    "\n",
    "    role = st.session_state.night_queue.pop(0)\n",
    "    st.session_state.current_night_role = role\n",
    "    \n",
    "    msg = f\"🌙 [{role}]은(는) 밤 행동을 취하십시오.\\n\"\n",
    "    if role == \"스파이\": msg += \"정체를 확인할 사람을 선택하세요.\"\n",
    "    elif role == \"마피아\": msg += \"죽일 사람을 선택하세요.\"\n",
    "    elif role == \"의사\": msg += \"살릴 사람을 선택하세요.\"\n",
    "    elif role == \"경찰\": msg += \"마피아로 의심되는 사람을 선택하세요.\"\n",
    "    elif role == \"기자\":\n",
    "        if st.session_state.day == 1:\n",
    "            msg = \"🚫 기자는 1일차 밤에는 취재할 수 없습니다. (다음 직업으로 넘어가세요)\"\n",
    "            st.session_state.current_night_role = \"기자_스킵\"\n",
    "        elif st.session_state.reporter_used:\n",
    "            msg = \"🚫 기자는 이미 특종을 냈습니다. (다음 직업으로 넘어가세요)\"\n",
    "            st.session_state.current_night_role = \"기자_스킵\"\n",
    "        else: msg += \"취재할 대상을 선택하세요. (내일 낮에 직업 공개)\"\n",
    "    elif role == \"탐정\": msg += \"추리할 대상을 선택하세요.\"\n",
    "    \n",
    "    st.session_state.sys_msgs = [msg]\n",
    "\n",
    "def cb_process_night_results():\n",
    "    log_msg(f\"☀️ {st.session_state.day}일차 아침이 밝았습니다.\")\n",
    "    \n",
    "    # 1. 마피아 살해, 의사 치료, 군인 방어\n",
    "    targets = st.session_state.night_targets\n",
    "    pinfo = st.session_state.players_info\n",
    "    \n",
    "    if \"마피아\" in targets:\n",
    "        target_pid = targets[\"마피아\"]\n",
    "        target_role = pinfo[target_pid]['role']\n",
    "        \n",
    "        if \"의사\" in targets and targets[\"의사\"] == target_pid:\n",
    "            log_msg(\"💉 의사의 활약으로 간밤에 아무도 죽지 않았습니다!\")\n",
    "        elif \"군인\" in target_role and pinfo[target_pid].get('shield', False):\n",
    "            pinfo[target_pid]['shield'] = False\n",
    "            log_msg(f\"🪖 군인(플레이어 {target_pid})님이 마피아의 공격을 버텼습니다!\")\n",
    "        else:\n",
    "            log_msg(f\"💀 밤 사이 플레이어 {target_pid}님이 사망했습니다.\")\n",
    "            kill_player(target_pid)\n",
    "    else:\n",
    "        log_msg(\"🕊️ 간밤에 아무도 죽지 않았습니다.\")\n",
    "\n",
    "    # 2. 기자 특종 발표\n",
    "    if st.session_state.reporter_target_day:\n",
    "        reporter_alive = any(\"기자\" in p['role'] for p in pinfo.values() if p['alive'])\n",
    "        if reporter_alive:\n",
    "            t_pid = st.session_state.reporter_target_day\n",
    "            t_role = pinfo[t_pid]['role']\n",
    "            log_msg(f\"📰 [특종] 기자에 의해 플레이어 {t_pid}님의 직업은 [{t_role}]로 밝혀졌습니다!\")\n",
    "        st.session_state.reporter_target_day = None\n",
    "\n",
    "    win = check_win()\n",
    "    if win: log_msg(f\"🏆 {win}\")\n",
    "\n",
    "def cb_toggle_day_night():\n",
    "    if st.session_state.is_night:\n",
    "        st.session_state.is_night = False\n",
    "        cb_process_night_results()\n",
    "    else:\n",
    "        st.session_state.day += 1\n",
    "        st.session_state.is_night = True\n",
    "        cb_start_night_phase()\n",
    "\n",
    "def cb_player_click(pid):\n",
    "    pinfo = st.session_state.players_info[pid]\n",
    "    target_role = pinfo['role']\n",
    "    c_role = st.session_state.current_night_role\n",
    "\n",
    "    if st.session_state.is_night and c_role:\n",
    "        if not pinfo['alive'] and c_role != \"의사\":\n",
    "            log_msg(\"⚠️ 죽은 사람은 선택할 수 없습니다.\")\n",
    "            return\n",
    "        if \"기자_스킵\" in c_role:\n",
    "            return\n",
    "\n",
    "        st.session_state.night_targets[c_role] = pid\n",
    "        \n",
    "        if c_role == \"스파이\":\n",
    "            if \"마피아\" in target_role:\n",
    "                st.session_state.spy_connected = True\n",
    "                log_msg(\"🤝 [시스템] 마피아와 접선 했습니다.\")\n",
    "            else:\n",
    "                log_msg(f\"👁️ [시스템] 플레이어 {pid}님은 [{target_role}] 입니다.\")\n",
    "        elif c_role == \"마피아\":\n",
    "            log_msg(f\"🔫 [시스템] 플레이어 {pid}님을 암살 대상으로 지정했습니다.\")\n",
    "        elif c_role == \"의사\":\n",
    "            log_msg(f\"💉 [시스템] 플레이어 {pid}님을 치료 대상으로 지정했습니다.\")\n",
    "        elif c_role == \"경찰\":\n",
    "            if \"마피아\" in target_role: log_msg(f\"🚨 [시스템] 플레이어 {pid}님은 마피아가 맞습니다!!\")\n",
    "            else: log_msg(f\"✅ [시스템] 플레이어 {pid}님은 마피아가 아닙니다.\")\n",
    "        elif c_role == \"기자\":\n",
    "            st.session_state.reporter_used = True\n",
    "            st.session_state.reporter_target_day = pid\n",
    "            log_msg(f\"📸 [시스템] 플레이어 {pid}님 취재 완료. (직업: {target_role})\")\n",
    "        elif c_role == \"탐정\":\n",
    "            t_action = None\n",
    "            for r, t_pid in st.session_state.night_targets.items():\n",
    "                if r in target_role: t_action = t_pid; break\n",
    "            if t_action: log_msg(f\"🔍 [시스템] 플레이어 {pid}님은 오늘 밤 [P{t_action}]님을 다녀갔습니다.\")\n",
    "            else: log_msg(f\"🔍 [시스템] 플레이어 {pid}님은 아무 행동도 하지 않았습니다.\")\n",
    "\n",
    "    elif not st.session_state.is_night:\n",
    "        kill_player(pid)\n",
    "        log_msg(f\"⚖️ 투표 결과: 플레이어 {pid}님이 처형되었습니다.\")\n",
    "        win = check_win()\n",
    "        if win: log_msg(f\"🏆 {win}\")\n",
    "\n",
    "\n",
    "# ==========================================\n",
    "# 3. 화면 UI 렌더링 (View)\n",
    "# ==========================================\n",
    "st.title(\"🕵️ 마피아 게임 도우미\")\n",
    "\n",
    "# --- SETUP PHASE ---\n",
    "if st.session_state.phase == 'setup':\n",
    "    with st.expander(\"📘 직업 설명 보기\"):\n",
    "        st.markdown(\"\"\"\n",
    "        - **마피아**: 밤마다 1명 암살\n",
    "        - **경찰**: 밤마다 마피아 여부 확인\n",
    "        - **의사**: 밤마다 1명 치료\n",
    "        - **스파이**: 마피아 찾으면 자동 접선\n",
    "        - **기자**: 2일차 밤부터 1명 취재(전체공개)\n",
    "        - **탐정**: 밤에 대상이 누구를 지목했는지 확인\n",
    "        - **정치인**: 투표 시 2표 행사\n",
    "        - **군인**: 마피아 공격 1회 방어\n",
    "        \"\"\")\n",
    "\n",
    "    col1, col2 = st.columns([1, 1])\n",
    "    with col1:\n",
    "        p_count = st.selectbox(\"인원수 설정\", [4, 5, 6, 7, 8], index=0)\n",
    "    with col2:\n",
    "        st.write(\"\") # 줄맞춤용\n",
    "        st.button(\"👥 설정 적용\", on_click=cb_set_roles, args=(p_count,), use_container_width=True)\n",
    "\n",
    "    st.divider()\n",
    "    \n",
    "    draw_disabled = len(st.session_state.roles) == 0\n",
    "    st.button(\"🎭 역할 뽑기 (스마트폰 돌려보기)\", on_click=cb_draw_role, disabled=draw_disabled, type=\"primary\", use_container_width=True)\n",
    "    \n",
    "    if st.session_state.sys_msgs:\n",
    "        st.info(st.session_state.sys_msgs[0])\n",
    "\n",
    "    if len(st.session_state.draw_log) == p_count and len(st.session_state.roles) == 0:\n",
    "        st.success(\"🎊 모든 역할이 배정되었습니다!\")\n",
    "        st.button(\"▶️ 게임 시작\", on_click=cb_start_game, type=\"primary\", use_container_width=True)\n",
    "        \n",
    "    with st.expander(\"📜 역할 뽑기 로그 (게임 마스터용)\"):\n",
    "        for log in st.session_state.draw_log:\n",
    "            st.text(log)\n",
    "\n",
    "\n",
    "# --- GAME PHASE ---\n",
    "elif st.session_state.phase == 'game':\n",
    "    \n",
    "    # 상단 컨트롤 패널\n",
    "    col_t1, col_t2, col_t3 = st.columns([1, 1.5, 1])\n",
    "    with col_t1:\n",
    "        st.button(\"🔄 리셋\", on_click=cb_reset, use_container_width=True)\n",
    "    with col_t2:\n",
    "        time_text = f\"🌙 {st.session_state.day}일차 밤\" if st.session_state.is_night else f\"☀️ {st.session_state.day}일차 낮\"\n",
    "        st.markdown(f\"<h3 style='text-align: center; margin:0;'>{time_text}</h3>\", unsafe_allow_html=True)\n",
    "    with col_t3:\n",
    "        st.button(\"⏭ 낮/밤 전환\", on_click=cb_toggle_day_night, type=\"secondary\", use_container_width=True)\n",
    "\n",
    "    # 스파이 접선 상태 표시\n",
    "    if any(\"스파이\" in p['role'] for p in st.session_state.players_info.values()):\n",
    "        if st.session_state.spy_connected:\n",
    "            st.success(\"🕶️ 스파이 접선 완료\")\n",
    "        else:\n",
    "            st.warning(\"🕶️ 스파이 접선 안됨\")\n",
    "\n",
    "    st.divider()\n",
    "\n",
    "    # 밤 행동 컨트롤\n",
    "    if st.session_state.is_night:\n",
    "        col_n1, col_n2 = st.columns([1, 3])\n",
    "        with col_n1:\n",
    "            st.button(\"▶️ 다음 직업\", on_click=cb_next_night_action, type=\"primary\", use_container_width=True)\n",
    "        with col_n2:\n",
    "            if st.session_state.current_night_role:\n",
    "                st.info(f\"현재 턴: **{st.session_state.current_night_role}**\")\n",
    "            else:\n",
    "                st.info(\"대기 중...\")\n",
    "\n",
    "    # 시스템 메시지 출력창\n",
    "    if st.session_state.sys_msgs:\n",
    "        with st.container(border=True):\n",
    "            for msg in st.session_state.sys_msgs[:3]: # 최신 3개만 표시\n",
    "                st.write(msg)\n",
    "\n",
    "    st.divider()\n",
    "    st.write(\"### 플레이어 목록 (행동/투표 대상 선택)\")\n",
    "\n",
    "    # 플레이어 버튼 그리드 생성 (모바일 최적화를 위해 2칸씩 배치)\n",
    "    cols = st.columns(2)\n",
    "    for idx, (pid, pinfo) in enumerate(st.session_state.players_info.items()):\n",
    "        col = cols[idx % 2]\n",
    "        role_name = pinfo['role']\n",
    "        is_alive = pinfo['alive']\n",
    "        \n",
    "        btn_label = f\"P{pid} ({role_name})\"\n",
    "        if not is_alive:\n",
    "            btn_label += \" 💀\"\n",
    "            \n",
    "        col.button(\n",
    "            btn_label, \n",
    "            key=f\"pbtn_{pid}\", \n",
    "            on_click=cb_player_click, \n",
    "            args=(pid,), \n",
    "            disabled=not is_alive,\n",
    "            use_container_width=True\n",
    "        )"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
